import socket

# Function which handles request generated by clients
def handle_request(request):

    headers = request.split('\n')
    filename = headers[0].split()[1]
    if filename == '/':
        filename = 'index.html' #this is our home

    try:
        fin = open(filename[1:])
        content = fin.read()
        fin.close()
        response = 'HTTP/1.0 200 OK\n\n' + content
        #This sends an OK message
    except FileNotFoundError:
        response = 'HTTP/1.0 404 NOT FOUND\n\nFile Not Found, please enter a valid Filename!!'
        #If file not found then send this

    return response

#This is teh IP address of teh virtual machine
SERVER_HOST = "192.168.1.63"
#This helkps ud to communicate between server and the client
SERVER_PORT = 8888

# These commands create a socket for us
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server_socket.bind((SERVER_HOST, SERVER_PORT))
server_socket.listen(1)
print('Listening on port %s ...' % SERVER_PORT)

while True:
    client_connection, client_address = server_socket.accept()
    request = client_connection.recv(1024).decode()
    print("Client is connected with Ip:",client_address)
    response = handle_request(request) #Return the response
    client_connection.sendall(response.encode())
    print("Client has disconnected with Ip:",client_address)
    client_connection.close()

server_socket.close() #Closes the socket
